docs/journalist/submissions.rst

Small change, but wanted to make sure we capture this. We unlock/mount/unmount/lock for each file. Note that the client currently does not display a success message -- that's very important, and part of https://github.com/freedomofpress/securedrop-client/pull/666

Clarify that USB drive can be unplugged after export

---

docs/admin/troubleshooting_connection.rst
docs/admin/troubleshooting_network.rst
docs/admin/workstation_architecture.rst
docs/index.rst

Ready for a first round review.
This adds a step-by-step troubleshooting how-to for resolving network issues with SecureDrop Workstation. It starts with the basics (is the Internet working) and goes all the way to restarting Tor, restarting VMs, etc.
The step-by-step format imposes some constraints, but it seems to me most suitable for this guide. Per this good blog post on [documentation best practices](https://www.divio.com/blog/documentation/) (thanks to @ninavizz for the link), I've offloaded explanatory content to a separate chapter about architecture.
Screenshots are deliberately omitted for now so we can take those still a little closer to the release date.

Add network troubleshooting guide

---

docs/admin/known_issues.rst
docs/includes/top-warning.rst
docs/index.rst
docs/journalist/faq.rst
docs/journalist/sources.rst
docs/journalist/starting_client.rst
docs/journalist/submissions.rst

- flesh out security FAQ
- updater now runs on login
- single click, not double click on files
- "Awaiting key" message and behavior updated per recent findings
and changes
- updater slowness a known issue
- misc. other edits

Full copyedit & updates pass

---

docs/admin/known_issues.rst
docs/journalist/ending_session.rst
docs/journalist/faq.rst
docs/journalist/submissions.rst

- Expand FAQ with missing entries
- Normal disposable VMs do allow copy and paste, so it's not quite
right to describe this as a general security limitation of Qubes.
We should explain our own copy and paste limitations separately.
- The "Log out" option was removed entirely due to its session-saving
behavior.
- Note that we do not support more than one Submission Key

Expand FAQ; updates and clarifications

---

docs/admin/install.rst

Adds a `sha256sum` check before installing the config RPM in `dom0`, to verify that it was copied successfully.

Add hash check for RPM post-dom0-transfer to install docs

---

docs/admin/install.rst

Closes #29 
Adds troubleshooting section in installation docs.

Added recovery steps for common install errors

---

docs/admin/install.rst

Closes #27 
Splits long command lines (mostly`qvm-run`commands) into multiple lines at logical breakpoints. Some code blocks still end up with horizontal scrollbars, but hopefully with improved overall readability.

Split long commands in install guide for improved readability

---

docs/admin/install.rst
docs/admin/managing_clipboard.rst
docs/admin/reviewing_logs.rst
docs/index.rst
docs/journalist/faq.rst

Ready for review. Depends on https://github.com/freedomofpress/securedrop-workstation/pull/533, which was released with SecureDrop Workstation 0.3.0.
I have tested the specific password manager instructions, but I do recommend re-testing those with the changes from  https://github.com/freedomofpress/securedrop-workstation/pull/533 in place.

Add section about post-install config: passwords, clipboard & logs

---

docs/admin/install.rst

Depends on https://github.com/freedomofpress/securedrop-workstation/pull/596, marked as draft until that's merged. Should not be tagged `stable` until updated RPM is released.
The same chapter of the docs updated here also refers to the Tails-based `securedrop-admin` tool, which illustrates why having a different name for the workstation tool is helpful to avoid confusion between the two.

Rename securedrop-admin to sdw-admin

---

docs/admin/troubleshooting_connection.rst

Fixes #56 
Run this command in both `sd-proxy` and `sd-whonix` of a working SecureDrop Workstation install to confirm that it works for both VMs.

Use wget instead of missing curl

---

docs/admin/upgrading_to_fedora_31.rst

Add an instruction for selecting the "Connect" option to connect directly to the Tor network when sys-whonix prompts for this. 
A screenshot of the qubes dialog would be ideal, so if other agree, I can modify the sys-whonix qubes settings in order to get it to prompt me again and then take a screenshot.

add instructions around sys-whonix tor connection

---

docs/admin/troubleshooting_connection.rst

Some of the steps did not appear in the sidebar due to being at the wrong hierarchy level.

Fix section hierarchy levels

---

docs/admin/install.rst

Ensures that all AppVMs and TemplateVMs have been fully rebooted,
prior to first run. Related to QA findings in [0].
[0] https://github.com/freedomofpress/securedrop-workstation/issues/630

Recommend reboot after first install

---

docs/admin/upgrading_to_fedora_31.rst

Adds a section in the `fedora-31` installation instructions, cribbed from the workaround in https://github.com/freedomofpress/securedrop-workstation/issues/485#issuecomment-595244676 , to pin the salt and salt-ssh packages in `fedora-31` at their initial versions.
This works around issue https://github.com/QubesOS/qubes-issues/issues/6188, but should be removed once a fix exists.

added temporary Salt pinning instructions for fedora-31

---

docs/admin/upgrading_to_fedora_31.rst

Includes the updated steps to pull in the test version of `qubes-mgmt-salt-vm-connector`,  as a more reasonable workaround for https://github.com/QubesOS/qubes-issues/issues/6188.

Documents use of test repos for qubes-mgmt-salt package

---

docs/admin/install.rst

Ready for review.
Resolves #71 
This is a very conservative approach that may involve rotation on some accounts that don't require it, but I think erring on the side of a simple procedure makes sense for the documentation; if folks want to discuss in more detail vis-a-vis an organization's specific procedures, that can be done in support.

Add pre-install task to rotate legacy passphrases

---

docs/admin/install.rst
docs/admin/upgrading_to_fedora_33.rst
docs/index.rst

- Removes references to v2 onion services, which are no longer supported
- Reinstate docs for updating the Fedora base template. Qubes 4.0.4 [includes fedora-32](https://www.qubes-os.org/news/2021/03/04/qubes-4-0-4/), which has reached EOL, so we're back in a position where it makes sense to recommend updating the template before proceeding with the install.
(Note: The Fedora removal never made it into a `stable` build of the docs - you have to browse `latest` to (not) see it.) 
Fixes #80

Remove v2 onion service docs; reinstate Fedora docs

---

docs/admin/known_issues.rst
docs/journalist/sources.rst

Thanks to https://github.com/freedomofpress/securedrop/pull/5954 we can remove references to 'flag for reply' in the docs.
Feedback welcome on whether this explanation for the journalist workflow seems accurate, including in cases where there is a surge of traffic to the servers as a new source is submitting something.

Remove flag-for-reply references from admin and journalist guides

---

docs/admin/backup.rst
docs/admin/install.rst
docs/index.rst

**Status** WIP/Ready for initial review
**Description** Document backup and restore process 
**Resolves** #46 
**Related** https://github.com/freedomofpress/securedrop-workstation/issues/120
The approach taken in this PR is to suggest backing up the vault vm and the configuration files from `dom0`, and nothing else. (See comms in linked issues above). 
I hope to improve on this approach eventually, because it's still a little unwieldy. Open questions include:
- Re-downloading and verifying the rpm and then shuttling it into dom0 seems like a real pain, but relying on a (potentially _very_ old) rpm + the updater also doesn't seem great. Currently, to be conservative, I recommend users re-download/verify/shuttle the RPM if it's not the current version. Open to feedback. 
- Currently, if …

Add backup and restore instructions

---

docs/admin/install.rst

Part of the 2021 signing key rotation epic (https://github.com/freedomofpress/securedrop/issues/5923).
This is blocked until we start signing releases with the new key, so draft for now.

Update signing key

---

docs/admin/install.rst
docs/admin/upgrading_fedora.rst
docs/index.rst

Towards https://github.com/freedomofpress/securedrop-workstation/issues/735
Makes the usual string substitutions. Also renames the fedora RST file so the URL is stable over time.
1. Visual review
2. `make docs` locally and ensure the renamed file is still reachable via clickable URLs in all the right places

Update fedora-33 -> fedora-34 throughout

---

docs/admin/install.rst

The HTTP header checks were necessary in case an admin hadn't run a
playbook since those changes were added. As of 2021-04, all admins have
run a playbook, due to the Ubuntu LTS migration to 20.04. We can safely
assume the Apache config is sufficiently up to date.

Remove apache header checks

---

docs/admin/hardware.rst
docs/admin/install.rst
docs/admin/upgrading_fedora.rst

Closes freedomofpress/securedrop-workstation#749 by documenting:
1. hardware compatibility, BIOS updates, and Qubes settings for the ThinkPad T14; and
2. a few extra steps necessary as of January 2022 now that both Fedora 32 and Whonix 15 are obsolete on arrival in new Qubes 4.0.4 installations.

documents ThinkPad T14 compatibility

---

docs/admin/install.rst

While we're working on a release that's compatible with R4.1, we want to make sure users keep installing Qubes OS 4.0.4. This also changes the link anchor to lead directly to the 4.0.4 release.

Add Qubes 4.1 (in-)compatibility note

---

.circleci/config.yml

Nightlies on this repo are failing more often than not, always about 2/3 of the way through the linkcheck command. 
This PR increases the no_output_timeout for this command from 10m to 30m.

Increased CI linkcheck timeout to 30min

---

docs/admin/backup.rst
docs/admin/install.rst
docs/admin/upgrading_fedora.rst

This does not include hardware-specific documentation updates or screenshot updates.
Partially resolves #104 (except for hardware-specific updates)
Resolves #108
Resolves #110 
Resolves #111
- Review visually for inconsistencies, errors, or parts of https://workstation.securedrop.org/ that haven't been updated yet but should be.
- Ideally, at least one person should try to perform a prod install following the revised docs.

Update documentation for Qubes 4.1

---

docs/admin/backup.rst

`descriptor` does not appear in config.json, `hostname` does.

Fix config check instructions in backup/restore guide

---

docs/admin/install.rst

`gedit` is no longer available on `fedora-36` and `gnome-text-editor` does not play nice with sudo yet.

Recommend nano instead of gedit

---

docs/admin/backup.rst

We want to write the tmp file to dom0, not inside vault. Also we need to
match for files in /tmp/ not files starting with /tmp
Fixes #117

Move some quotes and add a missing slash

---

docs/admin/backup.rst
docs/admin/hardware.rst
docs/admin/install.rst

- Sets `sys-usb` clarifications apart into their own section to mitigate confusion
- Updates description of `config.json` file to match its expected contents
- Replaces the recommendation to skip creating default VMs with a step to rename/delete VMs with conflicting names
- Adds the recommendation to avoid using a USB keyboard (if at all possible) to the hardware section
- Updates to `Qubes OS` name to be consistent

Clarifications to installation and restore docs

---

docs/admin/hardware.rst
docs/includes/iwlwifi/rc.local

Updates ThinkPad T14 hardware recommendations to reflect the 2nd-generation model compatible with Qubes 4.1, including how to install an `/rw/config/rc.local` script in `sys-net` to enable the Intel AX210 Wi-Fi controller.
Please do review this pull request locally via `make docs` and confirm that:
- The script in `includes/iwlwifi/rc.local`:

document Qubes 4.1 compatibility with 2nd-gen ThinkPad T14

---

.circleci/config.yml

This uses the Debian Bullseye image to mirror typical developer configurations, and is identical to the `securedrop-docs` configuration.

Use standard docs CI configuration

---

docs/admin/install.rst

Updates the install docs to reference Qubes 4.1.2 (links to download page and ISO filename references) as Qubes 4.1.1 is no longer available for download.

Update Qubes version in install instructions to 4.1.2

---

docs/_static/rtd_dark.css
docs/conf.py

Now that the main SecureDrop docs have had a responsive dark theme for a while in a stable release, and most of the issues have been worked out, I think it makes sense to bring this change to our other documentation portals.
This PR uses the same style sheet as the one for docs.securedrop.org, and works exactly the same (this just makes the experience consistent for workstation users).

Add a Dark Theme

---

docs/admin/backup.rst
docs/admin/install.rst

Changes: 
- Update link to Securedrop passphrase reset instructions
- Update link to `config.json.example`
Testing:

linkcheck fixes for our docs and new config.json.example location

---

docs/admin/hardware.rst
docs/admin/install.rst

Closes freedomofpress/securedrop-workstation#893.  Since this mini-HCL is becoming something of a garden of forking paths (insert this step for model X, prepend this step for model Y, ...), I've also taken the liberty of factoring out of some of the ~interventions~ sections that are no longer specific to the ThinkPad T series.

document ThinkPad X1 Carbon compatibility

---

deploy/Dockerfile

Equivalent of https://github.com/freedomofpress/securedrop-docs/pull/510 and https://github.com/freedomofpress/securedrop-dev-docs/pull/107
Works towards https://github.com/freedomofpress/infrastructure/issues/4407

Update python:3.9-slim-bullseye image sha, and switch to nginx:mainline-alpine-slim

---

docs/admin/troubleshooting_updates.rst

(Staying in draft mode til changes land)
Refs https://github.com/freedomofpress/securedrop-workstation/issues/934
Also threw in an update to fedora (37-> 38) since that was out of date as well

Update references to whonix (16->17) and Fedora (37->38)

---

docs/admin/troubleshooting_connection.rst

When the client loads, it tries to synchronize with the server, which may time out if there are a substantial number of sources.
This commit adds a section to the connection troubleshooting guide to advise on how to increase the timeout value.
Note: tested in browser with `make docs` and checked with `make docs-lint`

Document the process of increasing sync timeouts

---

docs/admin/troubleshooting_updates.rst

Refresh Whonix/Fedora references. The previous sample output was perfectly valid as an example, so this is really just to aid matching against the output folks on an up-to-date system are expected to see.

Update updater logs sample

---

docs/admin/troubleshooting_updates.rst

This PR adds the necessary steps to the update troubleshooting guide to let folks diagnose and correct an expired Release Signing Key.
It also fixes a random typo that I spotted while making this addition.

Document the process of replacing an expired signing key

---

docs/admin/install.rst
docs/admin/upgrading_fedora.rst

- Update docs to refer to Fedora-40 and fedora-40-xfce
- Did not update screenshots - see https://github.com/freedomofpress/securedrop-workstation-docs/issues/214
Refs https://github.com/freedomofpress/securedrop-workstation/issues/1077
Refs https://github.com/freedomofpress/securedrop-workstation/pull/1078 (Shouldn't be merged til this one is)

Update docs to reference Fedora 40

---

deploy/Dockerfile
poetry.lock
pyproject.toml

CI expected to fail until https://github.com/freedomofpress/securedrop-docs/pull/574 lands.

Switch to Bookworm & Python 3.11; update Alpine image; update deps

---

docs/general/known_issues.rst
docs/index.rst

Fixes #213 by moving the "Limitations and known issues" guide to the general section, rather than the Admin Guide.

Move limitations document to general section

---

docs/general/known_issues.rst

* webp is now supported.
* failed downloads are retried internally, but there's no manual retry mechanism yet.
* Remove link to now-archived `securedrop-export` repository

Update known issues for 4.2

---

docs/admin/install/troubleshoot.rst

Uninstalling isn't supported, just available as a developer tool.
Fixes #227.

Remove uninstall instructions for documentation

---

docs/admin/install/prepare.rst

Per QA, for now, Qubes 4.2 must be configured with American English for SDW install to go smoothly - this will be changed in a future version.
Refs https://github.com/freedomofpress/securedrop-workstation/issues/1148.

Document QubesOS English - American setup requirement (for now)

---

docs/admin/install/troubleshoot.rst
docs/admin/reference/hardware.rst

* Add `cpufreq=xen:hwp=off` full system freezes workaround
* Document the workaround for
<https://github.com/QubesOS/qubes-issues/issues/8825> by setting the
corresponding Xen command-line parameter by editing the grub menu to be
able to boot into a non-frozen state, and then the grub config itself to
persist the workaround.
* Move "Unable to reset PCI device" to Troubleshooting page
* Despite it only affecting specific hardware, this seems like a better
place to document it when people run into it during installation.
The only change to the text itself is that the dom0 terminal instructions
now refer to the Qubes 4.2 way of opening it.
Fixes #226.

Improve troubleshooting instructions

---

docs/general/known_issues.rst

At <https://github.com/freedomofpress/securedrop-workstation-docs/pull/231#issuecomment-2224013736> Nathan pointed out that since we're shipping `--uninstall`, we should document that it is incomplete.

Document uninstalling under known issues

---

docs/admin/install/install.rst
docs/admin/install/overview.rst
docs/admin/install/prepare.rst
docs/admin/install/troubleshoot.rst
docs/admin/reference/backup.rst
docs/admin/reference/hardware.rst
docs/admin/reference/managing_clipboard.rst
docs/admin/reference/provisioning_usb.rst
docs/admin/reference/securing_workstation.rst
docs/admin/reference/troubleshooting_connection.rst
docs/admin/reference/troubleshooting_updates.rst
docs/conf.py
docs/general/introduction.rst
docs/general/known_issues.rst
docs/general/status.rst
docs/general/workstation_architecture.rst
docs/includes/getting_support.rst
docs/includes/top-warning.rst
docs/index.rst
docs/journalist/ending_session.rst
docs/journalist/faq.rst
docs/journalist/sources.rst
docs/journalist/starting_client.rst
docs/journalist/starting_qubes.rst
docs/journalist/submissions.rst
pyproject.toml

This PR removes the top warnings (references to the SDW Pilot) and also bumps the version number to 1.0.0.
Closes #209

Remove top warnings and bump version to 1.0.0

---

docs/admin/reference/backup.rst

Update backup/restore guide with information about backing up sd-app and sd-gpg
(Will clean up and mark ready shortly)

Update backup/restore docs with sd-gpg, sd-app backup info

---

docs/admin/reference/backup.rst

Copy /usr/share/securedrop-workstation-dom0-config to the dom0 home directory before backup

Fixup: dom0 backup instructions

---

docs/general/known_issues.rst
docs/general/supported_filetypes.rst

And swap in `.eml` as our example of unsupported file type.

Document `heic` and `avif` file support

---

docs/admin/reference/backup.rst

Path is $RESTORE_DIR/securedrop-workstation-dom0-config, not $RESTORE_DIR/usr/share/securedrop-workstation-dom0-config

Update path to workstation-config directory in dom0 restore folder

---

docs/_static/rtd_dark.css
docs/admin/install/troubleshoot.rst
docs/admin/reference/backup.rst
docs/admin/reference/troubleshooting_connection.rst
docs/admin/reference/troubleshooting_updates.rst

- Fixes a few more menu references. I've standardized the text as much as possible to make it easier to search & replace in future.
- Fixes #249
- Resolves #221

Fix a few menu invocations & dark mode issue

---

docs/general/introduction.rst

If this kind of language works, could add similar language to main SD docs. I probably forgot some important shout-outs though!

Add introductory note crediting key open source components

---

docs/conf.py

* Skip all .onion URLs since Tor isn't set up
* The GNOME website returns a 403 from cloud networks, including the one GitHub Actions runs from.
* Same with the Lenovo support website, except it just times out.

Ignore some links that can't be checked in CI

---

docs/admin/reference/provisioning_usb.rst

Documents workaround for freedomofpress/securedrop-docs#599 after freedomofpress/securedrop-docs#628.

docs: warn about macOS 15 compatibility

---

docs/admin/reference/troubleshooting_updates.rst

docs: clarify key-update procedure

---

docs/admin/reference/provisioning_usb.rst

Now that we support it (c.f. https://github.com/freedomofpress/securedrop-workstation/issues/1267), recommend it to users since it supports larger files compared to FAT.

Recommend using exFAT for VeraCrypt drives

---

docs/admin/reference/troubleshooting_connection.rst
docs/admin/reference/troubleshooting_updates.rst
docs/general/introduction.rst
docs/general/workstation_architecture.rst

Fixes #341 
- Updates most references to whonix to reflect the change to Tor running directly in `sd-proxy` via  arti and without `sd-whonix`.
- There are still a few references to `whonix` as the default Qubes `whonix` templates are still present on the system, involved in updates, etc. 
- Also fixes a few stale references to fedora-41 and bullseye.
- By removing a stale troubleshooting step, this also fixes #309 
This change accounts for:

Docs update for initial removal of sd-whonix references
