README.md
Add more detailed breakdown of pyenv and pyenv-virtualenv install and setup for mac.
=> Add step by step macOS setup instructions

docs/admin/known_issues.rst, docs/admin/provisioning_usb.rst, docs/admin/securing_workstation.rst, docs/admin/troubleshooting_network.rst, docs/includes/top-warning.rst, docs/index.rst, docs/journalist/closing_client.rst, docs/journalist/introduction.rst, docs/journalist/sources.rst, docs/journalist/starting_client.rst, docs/journalist/starting_qubes.rst, docs/journalist/stopping_qubes.rst, docs/journalist/submissions.rst
Adds message to all pages via an include, indicating that the workstation is still in beta.
=> Added beta warning message to all pages

docs/admin/known_issues.rst, docs/admin/provisioning_usb.rst, docs/admin/securing_workstation.rst, docs/index.rst
Adds initial versions of the following:
- Admin:
- known issues
- securing the workstation
- provisioning USBs
=> Adds admin guide documentation

docs/journalist/faq.rst
Resolves #24.
Ready for review.
=> Explain copy and paste restriction

docs/admin/hardware.rst
Ready for review. Recommend commit-by-commit review as it includes whitespace cleanup.
Resolves #32 
Clarifies the specific impact of our recommended BIOS settings on the USB-C ports of the T480.
=> Clarify impact of our recommended BIOS settings on T480 ports

docs/admin/install.rst
Fixes #34. Recommend reviewing whitspace commit and main change separately for cleaner diffs.
Check the example output against output you get in Qubes `dom0` for a given submission key.
=> Clarify how to obtain Submission Key fingerprint

docs/admin/hardware.rst, docs/admin/install.rst
Closes #28 
Adds useful info for users choosing Tails as their working computer for the install process.
=> added notes to support use of Tails during the installation

docs/admin/install.rst
Closes #39 
Adds instructions on checking JI Apache config to verify that a >=0.13.0 playbook has been run.
=> added 0.13.0 config check to install docs

docs/admin/upgrading_to_fedora_31.rst
- Recommend whole system reboot as simplest way to ensure updates
are applied
- Mention Qube Template Manager for advanced users
- Consistent path references to Qubes Application Menu, similar to
style used in install docs
=> Tweaks to fedora-31 upgrade docs

docs/admin/hardware.rst
=> As of Tails 4.8, Unsafe Browser must be explicitly enabled

README.md
=> Explain build & tagging strategy in README

docs/admin/install.rst
4.3 -> 4.0.3, since 4.1 is still unreleased
=> Fixes Qubes version typo

README.md
Update README consistent with branch name change.
=> Update default branch name

.circleci/config.yml, docs/admin/install.rst
Fixes #93 
See the issue for details : )
=> Fix outdated reference to SecureDrop Release key

docs/conf.py
Update mainly to test build logic.
=> Bump copyright year

docs/admin/install.rst, docs/admin/upgrading_fedora.rst
See https://github.com/freedomofpress/securedrop-workstation/pull/774
=> Switch base template upgrade instructions from Fedora 34 to Fedora 35

docs/includes/top-warning.rst
Use same language as in https://github.com/freedomofpress/securedrop-workstation/pull/909
=> Standardize closed beta language

.github/workflows/ci.yml
This is needed for the [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions), and is nearly identical to the PR filed by @legoktm in https://github.com/freedomofpress/securedrop-dev-docs/pull/130
=> Run CI on "merge_group" events

docs/admin/known_issues.rst
Update known issues to address: 
- lack of download cancellation
- limited viewable filetypes
- UI performance with large numbers of sources
Modify key rotation info
=> Update known issues

docs/admin/install.rst, docs/admin/upgrading_fedora.rst, docs/index.rst
This is search & replace on the content removed in #115. I've re-tested it just now on 4.1.2 as well.
Resolves #186
=> Reinstate/refresh docs for upgrading Fedora prior to provisioning

docs/admin/install.rst, docs/admin/troubleshooting_updates.rst, docs/admin/upgrading_fedora.rst
Changes references from Fedora 38 to Fedora 39 throughout.
=> Update fedora references from -38 to -39

docs/admin/reference/troubleshooting_updates.rst
Now at `~/.securedrop_updater`.
=> Update path to updater logs

docs/admin/reference/troubleshooting_updates.rst
Should be 40 per 0c818fc7ef9bfa.
=> Update a few more Fedora 39 references

docs/general/status.rst
- general availability will be after 1.0.0
- general availability will be on the second half of 2024 and not mid-2024
=> Update general availability timeline

docs/admin/reference/hardware.rst
Advertise production requirements here; dev requirements can go in the dev docs.
Fixes #210.
=> Set a minimum of 32GB of RAM

docs/general/known_issues.rst, docs/general/status.rst, docs/general/supported_filetypes.rst, docs/index.rst
Add additional information to FAQ about:
- supported filetypes
- feature differences (in draft because I think there are some more things to call out/some language adjustments)
Update "is this right for you" to include a few more criteria.
=> Add feature and filetype information to FAQ

docs/admin/reference/backup.rst
Fixup restore_dir references throughout
=> Update remaining RESTORE_DIR reference

docs/general/known_issues.rst
"Currently, users..."
The suspense was killing me!
=> Remove a partial bullet point in the limitations guide

docs/index.rst
=> Link to onion service version on index

docs/admin/reference/backup.rst
Include our recommended path for custom template upgrades (rebuild instead of upgrade). Link to upstream dist-upgrade template-standalone-upgrade instructions.
=> Update backup/restore docs note about custom templates

docs/admin/install/overview.rst
=> Include note about LVFS and HP firmware woes in hardware recs

docs/admin/install/prepare.rst
=> Update install instructions for Qubes 4.2.3

docs/admin/reference/forensic_backup.rst, docs/index.rst
Add instructions on sd-log backup
=> Add instructions on accessing sd-log backup

.github/workflows/ci.yml, .github/workflows/linkcheck.yml, deploy/Dockerfile, pyproject.toml
Follow-up from https://github.com/freedomofpress/securedrop-docs/pull/663
=> Migrate to Debian Trixie

docs/journalist/sources.rst
Resolves https://github.com/freedomofpress/securedrop-client/issues/1190
=> Explain how failed replies are handled

docs/general/introduction.rst
Motivated by <https://lwn.net/Articles/1031701/> and <https://securedrop.org/news/implementing-just-works-printing-in-securedrop-workstation/>.
=> Mention we rely on OpenPrinting

docs/admin/install/install.rst, docs/admin/install/troubleshoot.rst
Fixes #331 
This change accounts for:
=> install: document sdw-admin --configure
